import Head from "next/head";
import Image from "next/image";
import About from "../components/about/About";
import Main from "../components/main/Main";
import NavBar from "../components/navbar/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Liisi | Front End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Main />
      <About />
    </div>
  );
}
